# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values?hl=ja
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_CRJ_SERVICE_NAME}:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_CRJ_SERVICE_NAME}:$COMMIT_SHA']
# Delete existing Cloud Run job
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'beta', 'run', 'jobs', 'delete', '${_CRJ_SERVICE_NAME}', '--region', '${_CRJ_REGION}', '--quiet' # --quite: エラーや警告などの詳細なメッセージを非表示表示
  ]
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'beta', 'run', 'jobs', 'create', '${_CRJ_SERVICE_NAME}', 
    '--image', 'gcr.io/$PROJECT_ID/${_CRJ_SERVICE_NAME}:$COMMIT_SHA', 
    '--set-cloudsql-instances','${_CLOUD_SQL_INSTANCE}',
    '--tasks', '${_CRJ_TASKS}',
    '--max-retries', '${_CRJ_MAX_RETRIES}',
    '--task-timeout', '${_CRJ_TASK_TIMEOUT}',
    '--parallelism', '${_CRJ_PARALLELISM}',
    '--cpu', '${_CRJ_CPU}',
    '--memory', '${_CRJ_MEMORY}',
    '--region', '${_CRJ_REGION}',
    '--set-env-vars', 'CLOUD_SQL_USER=${_CLOUD_SQL_USER}',
    '--set-env-vars', 'CLOUD_SQL_PASSWORD=${_CLOUD_SQL_PASSWORD}',
    '--set-env-vars', 'CLOUD_SQL_NAME=${_CLOUD_SQL_NAME}',
    '--set-env-vars', 'CLOUD_SQL_INSTANCE=${_CLOUD_SQL_INSTANCE}',
    '--set-env-vars', 'LINE_NOTIFY_TOKEN=${_LINE_NOTIFY_TOKEN}',
    '--set-env-vars', 'FROM_EMAIL=${_FROM_EMAIL}',
    '--set-env-vars', 'FROM_PASSWORD=${_FROM_PASSWORD}',
    '--set-env-vars', 'TO_EMAIL=${_TO_EMAIL}',
  ]
images:
- 'gcr.io/$PROJECT_ID/${_CRJ_SERVICE_NAME}:$COMMIT_SHA'