steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_CR_SERVICE_NAME}:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_CR_SERVICE_NAME}:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', '${_CR_SERVICE_NAME}', 
    '--image', 'gcr.io/$PROJECT_ID/${_CR_SERVICE_NAME}:$COMMIT_SHA', 
    '--region', '${_CR_REGION}',
    '--allow-unauthenticated', # 
    '--add-cloudsql-instances','${_CLOUD_SQL_INSTANCE}',
    '--update-env-vars', 'CLOUD_SQL_USER=${_CLOUD_SQL_USER}',
    '--update-env-vars', 'CLOUD_SQL_PASSWORD=${_CLOUD_SQL_PASSWORD}',
    '--update-env-vars', 'CLOUD_SQL_NAME=${_CLOUD_SQL_NAME}',
    '--update-env-vars', 'CLOUD_SQL_INSTANCE=${_CLOUD_SQL_INSTANCE}'
    ]
images:
- 'gcr.io/$PROJECT_ID/${_CR_SERVICE_NAME}:$COMMIT_SHA'